CREATE TABLE IF NOT EXISTS DRONE (
            SERIAL_NUMBER INTEGER NOT NULL,
            MODEL VARCHAR (50),
            WEIGHT_LIMIT INTEGER,
            BATTERY_CAPACITY INTEGER,
            STATE VARCHAR (50),
            PRIMARY KEY (SERIAL_NUMBER));

CREATE TABLE IF NOT EXISTS MEDICINE (
            NAME VARCHAR (50) NOT NULL,
            WEIGHT INTEGER,
            CODE VARCHAR (50),
            IMAGE_URL VARCHAR (50),
            PRIMARY KEY (NAME));

CREATE TABLE IF NOT EXISTS DRONE_MEDICINE_ASSOCIATION (
            DRONE_SERIAL_NUMBER VARCHAR (50) NOT NULL,
            MEDICINE_NAME VARCHAR (50) NOT NULL,
            MEDICINE_COUNT INTEGER,
            FOREIGN KEY (DRONE_SERIAL_NUMBER) REFERENCES DRONE(SERIAL_NUMBER) ON DELETE CASCADE,
            FOREIGN KEY (MEDICINE_NAME) REFERENCES MEDICINE(NAME) ON DELETE CASCADE,
            UNIQUE (SERIAL_NUMBER, NAME));
